---
driver:
  name: ec2
  instance_type: t2.micro

transport:
  username: ubuntu

provisioner:
  name: shell

platforms:
  - name: ubuntu
    driver: 
      image_id: ami-0e431df20c101e6b7
      region: us-east-2

verifier:
  name: inspec

suites:
- name: default